[package]
name = "learn_RAST"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
reqwest = { version = "0.12.22", features = ["json", "rustls-tls"] }
futures = "0.3"
